### ISSUE TITLE
logo image not showing up after refresh

### ISSUE THREAD

**Issue by ashishapy** [heliumink/vitaink#4]
- [ ] Logo image is not showing after refresh of browser when navigating to some nested urls like http://vitaink.meteor.com/mentor/requirements. 

- [ ] The same issue us replicated when user tries to go to directly by typing url http://vitaink.meteor.com/mentor/requirements on address bar.

<img width="535" alt="logoerror" src="https://cloud.githubusercontent.com/assets/6279997/9366901/ba67f542-46d7-11e5-8552-4c7a90f0eafd.png">

**Comment by mrinalpande** [comment]
![screenshot 37](https://cloud.githubusercontent.com/assets/8715107/9727209/125a406a-561a-11e5-9c65-701c43214fb7.png)
The Issue is also with the footer image, I guess it is something to do image path. Will be looking into it.

**Comment by ashishapy** [comment]
Fixed as part of commit https://github.com/heliumink/vitaink/commit/715c36ef092d7c82f0704a0c2bb4cceb0aeb2a11
